#!/usr/bin/env python3
"""Build a single-file AtlasOS web installer for LuaMade httpget installs."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = REPO_ROOT / "dist" / "atlasos-web-installer.lua"
SOURCE_ROOTS = (
    (REPO_ROOT / "AtlasOS", "/home/AtlasOS"),
    (REPO_ROOT / "Lib", "/home/lib"),
)
CORE_PATHS = (
    "/home/AtlasOS/installer_gate.lua",
    "/home/AtlasOS/installer_ui.lua",
    "/home/AtlasOS/boot_desktop.lua",
    "/home/AtlasOS/shell.lua",
    "/home/AtlasOS/ui.lua",
    "/home/lib/startmenu.lua",
    "/home/lib/atlasgfx.lua",
    "/home/lib/atlasinstall.lua",
    "/home/lib/atlasprofile.lua",
    "/home/lib/atlastheme.lua",
)
STARTUP_BODY = """-- AtlasOS auto-start (LuaMade runs this at boot; see Logiscript \"Startup behavior\")
local function atlas_run(path)
  if type(dofile) == \"function\" then
	return dofile(path)
  end
  if type(loadfile) == \"function\" then
	local chunk, err = loadfile(path)
	if not chunk then error(err) end
	return chunk()
  end
  error(\"AtlasOS startup: no script loader available (dofile/loadfile missing)\")
end

atlas_run(\"/home/AtlasOS/installer_gate.lua\")
"""


@dataclass(frozen=True)
class BundleFile:
    source: Path
    destination: str
    body: str


def lua_long_string(raw: str) -> str:
    for eq_count in range(0, 32):
        open_delim = "[" + ("=" * eq_count) + "["
        close_delim = "]" + ("=" * eq_count) + "]"
        if close_delim not in raw:
            return f"{open_delim}{raw}{close_delim}"
    raise ValueError("could not find a safe Lua long-string delimiter")


def iter_bundle_files() -> Iterable[BundleFile]:
    for source_root, destination_root in SOURCE_ROOTS:
        if not source_root.is_dir():
            raise FileNotFoundError(f"missing source directory: {source_root}")
        for path in sorted(p for p in source_root.rglob("*") if p.is_file()):
            rel = path.relative_to(source_root).as_posix()
            destination = f"{destination_root}/{rel}"
            body = path.read_text(encoding="utf-8")
            yield BundleFile(source=path, destination=destination, body=body)


def render_installer(bundle_files: list[BundleFile]) -> str:
    total_bytes = sum(len(item.body.encode("utf-8")) for item in bundle_files)

    lines: list[str] = []
    lines.append("-- Auto-generated by scripts/build_web_installer.py. Do not edit by hand.")
    lines.append("-- AtlasOS web installer for LuaMade httpget installs.")
    lines.append("-- Suggested in-game command:")
    lines.append("--   httpget <hosted-url>/atlasos-web-installer.lua /etc/startup.lua")
    lines.append("--   reboot")
    lines.append("")
    lines.append('local MARKER = "ATLASOS_WEB_INSTALLER_V1"')
    lines.append('local STARTUP_PATH = "/etc/startup.lua"')
    lines.append('local STARTUP_BACKUP = "/etc/startup.lua.atlasos_backup"')
    lines.append(f"local NORMAL_STARTUP = {lua_long_string(STARTUP_BODY)}")
    lines.append("local CORE_PATHS = {")
    for path in CORE_PATHS:
        lines.append(f"\t{lua_long_string(path)},")
    lines.append("}")
    lines.append("")
    lines.append(f"local BUNDLE_FILE_COUNT = {len(bundle_files)}")
    lines.append(f"local BUNDLE_TOTAL_BYTES = {total_bytes}")
    lines.append("local BUNDLE = {")
    for item in bundle_files:
        lines.append("\t{")
        lines.append(f"\t\tpath = {lua_long_string(item.destination)},")
        lines.append(f"\t\tbody = {lua_long_string(item.body)},")
        lines.append("\t},")
    lines.append("}")
    lines.append("")
    lines.append(
        """
local function normalize(path)
	path = tostring(path or "")
	path = path:gsub("\\\\", "/")
	path = path:gsub("/+", "/")
	if path == "" then return "/" end
	if #path > 1 and path:sub(-1) == "/" then path = path:sub(1, -2) end
	return path
end

local function ensure_parent_dir(path)
	path = normalize(path)
	local parent = path:match("^(.+)/[^/]+$")
	if not parent or parent == "" or parent == "/" then return true end
	local acc = ""
	for part in parent:gmatch("[^/]+") do
		acc = (acc == "") and ("/" .. part) or (acc .. "/" .. part)
		if fs.makeDir then
			local ok, err = pcall(fs.makeDir, acc)
			if not ok then return false, err end
		end
	end
	return true
end

local function read_file(path)
	local ok, raw = pcall(fs.read, normalize(path))
	if ok then return raw end
	return nil
end

local function write_file(path, body)
	local ok_dir, err_dir = ensure_parent_dir(path)
	if not ok_dir then return false, err_dir end
	local ok, err = pcall(fs.write, normalize(path), body)
	if not ok then return false, err end
	return true
end

local function verify_core_paths()
	local missing = {}
	for _, path in ipairs(CORE_PATHS) do
		if read_file(path) == nil then
			missing[#missing + 1] = path
		end
	end
	return missing
end

local function run_script(path)
	if type(dofile) == "function" then
		return dofile(path)
	end
	if type(loadfile) == "function" then
		local chunk, err = loadfile(path)
		if not chunk then
			error("could not load " .. tostring(path) .. ": " .. tostring(err))
		end
		return chunk()
	end
	error("no script loader available (dofile/loadfile missing)")
end

local function looks_like_atlas_startup(body)
	body = tostring(body or "")
	return body:find("installer_gate.lua", 1, true)
		or body:find("boot_desktop.lua", 1, true)
		or body:find("AtlasOS", 1, true)
end

local function install_startup_hook()
	local prev = read_file(STARTUP_PATH)
	if prev and prev:gsub("%s", "") ~= "" and not prev:find(MARKER, 1, true) and not looks_like_atlas_startup(prev) then
		local ok_backup, err_backup = write_file(STARTUP_BACKUP, prev)
		if not ok_backup then
			return false, "could not write startup backup: " .. tostring(err_backup)
		end
		print("Backed up previous startup to " .. STARTUP_BACKUP)
	end
	local ok, err = write_file(STARTUP_PATH, NORMAL_STARTUP)
	if not ok then
		return false, "could not write startup hook: " .. tostring(err)
	end
	return true
end

local function write_bundle()
	local wrote, skipped = 0, 0
	for index, item in ipairs(BUNDLE) do
		local current = read_file(item.path)
		if current == item.body then
			skipped = skipped + 1
		else
			local ok, err = write_file(item.path, item.body)
			if not ok then
				return false, "failed to write " .. tostring(item.path) .. ": " .. tostring(err)
			end
			wrote = wrote + 1
		end
		if index == 1 or index == #BUNDLE or index % 10 == 0 then
			print(string.format("[%d/%d] %s", index, #BUNDLE, item.path))
		end
	end
	return true, wrote, skipped
end

local function main()
	print("AtlasOS web installer")
	print(string.format("Bundle: %d files, %d bytes", BUNDLE_FILE_COUNT, BUNDLE_TOTAL_BYTES))
	print("")

	local ok_bundle, wrote, skipped = write_bundle()
	if not ok_bundle then
		error(wrote)
	end
	print(string.format("Wrote %d file(s); %d already up to date.", wrote, skipped))

	local missing = verify_core_paths()
	if #missing > 0 then
		print("")
		for _, path in ipairs(missing) do
			print("Missing required file: " .. path)
		end
		error("bundle verification failed")
	end

	local ok_startup, startup_err = install_startup_hook()
	if not ok_startup then
		error(startup_err)
	end

	print("Startup hook installed at " .. STARTUP_PATH)
	print("Launching AtlasOS…")
	print("")
	run_script("/home/AtlasOS/installer_gate.lua")
end

local ok, err = pcall(main)
if not ok then
	print("AtlasOS web install failed: " .. tostring(err))
end
""".strip("\n")
    )
    lines.append("")
    return "\n".join(lines) + "\n"


def build(output: Path) -> Path:
    bundle_files = list(iter_bundle_files())
    rendered = render_installer(bundle_files)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered, encoding="utf-8")
    return output


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=OUTPUT_PATH,
        help=f"output Lua file (default: {OUTPUT_PATH.relative_to(REPO_ROOT)})",
    )
    args = parser.parse_args()

    output = build(args.output.resolve())
    bundle_files = list(iter_bundle_files())
    print(f"Built {output}")
    print(f"Bundled {len(bundle_files)} files from AtlasOS/ and Lib/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

